package me.CubeLegend.TheManHunt.LanguageSystem;

public enum Message {

    //Command Team
    ERROR_ONLY_FOR_PLAYERS,
    ERROR_INVALID_TEAM,
    ERROR_GAME_IS_RUNNING,
    ERROR_GAME_IS_NOT_RUNNING,
    ERROR_PLAYER_IS_NOT_ONLINE,
    ERROR_NOT_ENOUGH_TEAM_MEMBERS,
    ERROR_USE_ONLY_IN_OVERWORLD,
    YOU_JOINED_TEAM,
    YOU_LEFT_TEAM,
    OTHER_PLAYER_ADDED_TO_TEAM,
    OTHER_PLAYER_REMOVED_FROM_TEAM,
    MEMBERS_OF_TEAM_LISTED,
    GAME_STOPPED,
    HUNTER_NEAR,
    COMPASS_POINTS_TO,
    NEXT_VILLAGE_X_BLOCKS_AWAY,
    TEAM_HAS_WON,
    HUNTERS_RELEASED,
    TIME_UNTIL_HUNTERS_RELEASED
}
