package me.CubeLegend.TheManHunt.LanguageSystem;

public enum Message {

    //Command Team
    ERROR_ONLY_FOR_PLAYERS,
    ERROR_INVALID_TEAM,
    ERROR_GAME_IS_RUNNING,
    ERROR_PLAYER_IS_NOT_ONLINE,
    ERROR_NOT_ENOUGH_TEAM_MEMBERS,
    YOU_JOINED_TEAM,
    YOU_LEFT_TEAM,
    OTHER_PLAYER_ADDED_TO_TEAM,
    OTHER_PLAYER_REMOVED_FROM_TEAM,
    MEMBERS_OF_TEAM_LISTED
}
