# Delete the world on startup to generate a new one if a run was finished on that world.
DeleteWorldOnStartUp: true
DeleteDatapacksOnStartUp: false

Default:
  Language: "english"
  GameMode: "powered_up"

# Set how text should look like
Message:
  DefaultColor: ["GOLD"]
  HighlightedColor: ["GOLD", "UNDERLINE", "BOLD"]
  ErrorColor: ["RED"]
  ErrorHighlightedColor: ["RED", "UNDERLINE", "BOLD"]

# How long the
Title:
  FadeIn: 50
  Stay: 50
  FadeOut: 50

# How long hunters need to wait at the beginning of the game (in seconds).
HunterWaitTimer: 10

HunterNearWarningRadius: 50

# Set how often features should be updated, setting this slower can feel laggy.
# 1 means every tick, 2 means every other tick and so on.
UpdatePeriod:
  FreezeVision: 1
  HunterNearWarning: 1
  FortressTracker: 1
  VillageTracker: 1
  RunnerTracker: 1
  CompassSpinning: 1

# Always give the player a compass with an updated lodestone position, even if the runner hasn't moved.
AlwaysUpdateRunnerTracker: true
# Also set a Lodestone in Overworld, for consistency reasons.
AlwaysSetLodestone: false

VillageTrackerUseLodestone: false

# Set true to give everyone the selected permissions.
# OPs can always use everything.
# This should probably be empty if you use a permission management plugin.
GiveEveryonePermissions: ["Players.CmdTeamJoin", "Players.CmdTeamList", "Players.CmdLanguage", "GameManagement.CmdGame"]
