PluginMessagingChannelOfMiniGame: "themanhunt:minigame"
DeleteWorldOnStartUp: false

DefaultMessageColor: ["GOLD"]
HighlightedMessageColor: ["GOLD", "UNDERLINE", "BOLD"]
ErrorMessageColor: ["RED"]
ErrorHighlightedMessageColor: ["RED", "UNDERLINE", "BOLD"]

TitleFadeIn: 50
TitleStay: 50
TitleFadeOut: 50

DefaultLanguage: "English"

FreezeVision: false
OneHitKill: false
HunterNearWarning: false
VillageTracker: false
RunnerTracker: false

HunterWaitTimer: 10
HunterNearWarningRadius: 50

FreezeVisionUpdatePeriod: 1
HunterNearWarningUpdatePeriod: 1
VillageTrackerUpdatePeriod: 1
RunnerTrackerUpdatePeriod: 1
CompassSpinningUpdatePeriod: 1

AlwaysUpdateRunnerTracker: true
AlwaysSetLodestone: false

VillageTrackerUseLodestone: false