PluginMessagingChannelOfMiniGame: "themanhunt:minigame"
DeleteWorldOnStartUp: false

DefaultMessageColor: ["GOLD"]
HighlightedMessageColor: ["GOLD", "UNDERLINE", "BOLD"]
ErrorMessageColor: ["RED"]
ErrorHighlightedMessageColor: ["RED", "UNDERLINE", "BOLD"]

TitleFadeIn: 50
TitleStay: 50
TitleFadeOut: 50

DefaultLanguage: "English"

FreezeVision: false
OneHitKill: false
HunterNearWarning: false
VillageTracker: false
RunnerTracker: false

HunterWaitTimer: 10
HunterNearWarningRadius: 50

FreezeVisionUpdatePeriod: 1
HunterNearWarningUpdatePeriod: 1
VillageTrackerUpdatePeriod: 1
RunnerTrackerUpdatePeriod: 1
CompassSpinningUpdatePeriod: 1

AlwaysUpdateRunnerTracker: true
AlwaysSetLodestone: false

VillageTrackerUseLodestone: false

# Set true to give everyone the selected permissions.
# OPs can always use everything.
# This should probably only be used if you don't hava a permission management plugin.
GiveEveryonePermissions: ["Players.CmdTeamJoin", "Players.CmdTeamList", "Players.CmdLanguage", "GameManagement.CmdGame"]
