# Delete the world on startup to generate a new one if a run was finished on that world.
DeleteWorldOnStartUp: true
# Whether the Datapacks directory should also be deleted, when the world gets deleted.
DeleteDatapacksOnStartUp: false

Default:
  # Set the default language for new players.
  Language: "english"
  # Set the default game mode, when starting the server.
  GameMode: "powered up"

# Set how text should look like.
Message:
  DefaultColor: ["GOLD"]
  HighlightedColor: ["GOLD", "UNDERLINE", "BOLD"]
  ErrorColor: ["RED"]
  ErrorHighlightedColor: ["RED", "UNDERLINE", "BOLD"]

# How long the win/lose title should stay on the screen.
Title:
  FadeIn: 50
  Stay: 50
  FadeOut: 50

Teams:
  Runners:
    # What Slot the icon should be in the team selection gui. Note that two icons cannot be on the same slot.
    SelectionSlot: 2
    # What item the team should be displayed as in the team selection gui.
    Icon: "diamond_shovel"
    # What color the names of the team members have.
    Color: "blue"
  Hunters:
    # What Slot the icon should be in the team selection gui. Note that two icons cannot be on the same slot.
    SelectionSlot: 4
    # What item the team should be displayed as in the team selection gui.
    Icon: "diamond_sword"
    # What color the names of the team members have.
    Color: "red"
  Spectators:
    # What Slot the icon should be in the team selection gui. Note that two icons cannot be on the same slot.
    SelectionSlot: 6
    # What item the team should be displayed as in the team selection gui.
    Icon: "gray_stained_glass"
    # What color the names of the team members have.
    Color: "gray"

# How long hunters need to wait at the beginning of the game (in seconds).
HunterWaitTimer: 10

# Set how often features should be updated, setting this slower can feel laggy.
# 1 means every tick, 2 means every other tick and so on.
UpdatePeriod:
  FreezeVision: 1
  HunterNearWarning: 1
  FortressTracker: 1
  VillageTracker: 1
  RunnerTracker: 1
  CompassSpinning: 1

# Always give the player a compass with an updated lodestone position, even if the runner hasn't moved.
AlwaysUpdateRunnerTracker: true
# Also set a Lodestone in Overworld.
# Useful for consistency reasons or to preserve the default functionality of normal compasses.
AlwaysSetLodestone: false
# Also set update the VillageTracker with lodestones.
# Useful for consistency reasons or to preserve the default functionality of normal compasses.
VillageTrackerUseLodestone: false

# Set true to give everyone the selected permissions.
# OPs can always use everything.
# This should probably be empty if you use a permission management plugin.
GiveEveryonePermissions: ["Players.CmdTeamJoin", "Players.CmdTeamList", "Players.CmdLanguage", "GameManagement.CmdGame"]
