PluginMessagingChannelOfMiniGame: "themanhunt:minigame"

# Delete the world on startup to generate a new one if a run was finished on that world.
DeleteWorldOnStartUp: true
DeleteDatapacksOnStartUp: false

# Set how text should look like
DefaultMessageColor: ["GOLD"]
HighlightedMessageColor: ["GOLD", "UNDERLINE", "BOLD"]
ErrorMessageColor: ["RED"]
ErrorHighlightedMessageColor: ["RED", "UNDERLINE", "BOLD"]

# How long the
TitleFadeIn: 50
TitleStay: 50
TitleFadeOut: 50

DefaultLanguage: "english"

# Turn special abilities on or off.
FreezeVision: false
OneHitKill: false
HunterNearWarning: false
VillageTracker: false
RunnerTracker: false

# How long hunters need to wait at the beginning of the game (in seconds).
HunterWaitTimer: 10

HunterNearWarningRadius: 50

# Set how often features should be updated, setting this slower can feel laggy.
# 1 means every tick, 2 means every other tick and so on.
FreezeVisionUpdatePeriod: 1
HunterNearWarningUpdatePeriod: 1
VillageTrackerUpdatePeriod: 1
RunnerTrackerUpdatePeriod: 1
CompassSpinningUpdatePeriod: 1

# Always give the player a compass with an updated lodestone position, even if the runner hasn't moved.
AlwaysUpdateRunnerTracker: true
# Also set a Lodestone in Overworld, for consistency reasons.
AlwaysSetLodestone: false

VillageTrackerUseLodestone: false

# Set true to give everyone the selected permissions.
# OPs can always use everything.
# This should probably be empty if you use a permission management plugin.
GiveEveryonePermissions: ["Players.CmdTeamJoin", "Players.CmdTeamList", "Players.CmdLanguage", "GameManagement.CmdGame"]
