name: TheManHunt
version: ${project.version}
author: CubeLegend
main: me.CubeLegend.TheManHunt.TheManHunt
api-version: 1.16
load: POSTWORLD

commands:
  game:
    description: Starts the game if it isn't already running and if it there are enough players in the Teams
    usage: /game <start|stop>

  team:
    description: To join a team, list members of a team, add or remove a player from a team
    usage: /team <join|list|add|remove> [<Player Name>] <Team Name>

  language:
    description: To select your language
    usage: /language <language>
