name: TheManHunt
version: 0.1
author: CubeLegend
main: me.CubeLegend.TheManHunt.TheManHunt
api-version: 1.16

commands:
  start:
    description: Starts the game if it isn't allready running and if it there are enough players in the Teams
    usage: /start
    permission: TheManHunt.GameManagement

  MembersOf:
  Dev:
  VectorOf:
  CrossProduct:
  DotProduct:
  showLine: